#!/usr/bin/env python3
"""
LOTUS Snack 2026 — Update Dashboard
Read JSON from scraper → inject into KOL_DATA in index.html
Usage: python3 scripts/update_dashboard.py scrape_results.json index.html
"""

import json
import sys
import re

# ============================================================
#  KOL METADATA — fallback data for all KOLs (generated by skill)
# ============================================================
KOL_METADATA = {
    "markc.boardgame": {
        "displayName": "markc.boardgame",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 104900,
        "budget": 12000
    },
    "minkmories": {
        "displayName": "minkmories",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 363400,
        "budget": 15000
    },
    "dairyparty": {
        "displayName": "dairyparty",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 68700,
        "budget": 10000
    },
    "narongrit11414": {
        "displayName": "narongrit",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 85700,
        "budget": 16000
    },
    "tanawatpankaew": {
        "displayName": "tanawatpankaew",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 77400,
        "budget": 5000
    },
    "fford._.mini": {
        "displayName": "fford._.mini",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 23200,
        "budget": 7000
    },
    "ledswu": {
        "displayName": "ledswu",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 138400,
        "budget": 17000
    },
    "debuam012": {
        "displayName": "debuam012",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 20600,
        "budget": 4500
    },
    "saruanly": {
        "displayName": "saruanly",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 6639,
        "budget": 7250
    },
    "tuajeed.office": {
        "displayName": "tuajeed.office",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 27000,
        "budget": 14500
    },
    "miinez_": {
        "displayName": "miinez_",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 39100,
        "budget": 15000
    },
    "gonsalosol": {
        "displayName": "gonsalosol",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 372900,
        "budget": 26000
    },
    "sharkwow.ch": {
        "displayName": "sharkwow.ch",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 578300,
        "budget": 40000
    },
    "witbenmoreallright": {
        "displayName": "witbenmoreallright",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 1000000,
        "budget": 35000
    },
    "gampamao": {
        "displayName": "ไอ้แก้มขี้เมา",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 182600,
        "budget": 15000
    },
    "tatatomang": {
        "displayName": "tatatomang",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 186900,
        "budget": 15000
    },
    "taloncamp_sg": {
        "displayName": "ตะลอนแคมภ์",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 257100,
        "budget": 19000
    },
    "sarun_kritaterakul": {
        "displayName": "sarun_kritaterakul",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 30600,
        "budget": 9000
    },
    "nattienote": {
        "displayName": "nattienote",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 274900,
        "budget": 22000
    }
}

KOL_LINKS = {
    "markc.boardgame": "https://vt.tiktok.com/ZS9aPr8MX/",
    "minkmories": "https://vt.tiktok.com/ZS9bLxokr/",
    "dairyparty": "https://vt.tiktok.com/ZS9nKRULc/",
    "narongrit11414": "https://vt.tiktok.com/ZS9EsqqWw/",
    "tanawatpankaew": "https://vt.tiktok.com/ZS9KqJggx/",
    "fford._.mini": "https://vt.tiktok.com/ZS9bMV5M5/",
    "ledswu": "https://vt.tiktok.com/ZS9G9rGKX/",
    "debuam012": "https://vt.tiktok.com/ZS9bFpyNh/",
    "saruanly": "https://vt.tiktok.com/ZS9a2kjxW/",
    "tuajeed.office": "https://vt.tiktok.com/ZSxjfekwg/",
    "miinez_": "https://vt.tiktok.com/ZS9tk5kKo/",
    "gonsalosol": "https://vt.tiktok.com/ZSx8JCwkq/",
    "sharkwow.ch": "https://vt.tiktok.com/ZS9Kq6Fbf/",
    "witbenmoreallright": "https://vt.tiktok.com/ZS9aABnfe/",
    "gampamao": "https://vt.tiktok.com/ZS9aSw6mn/",
    "tatatomang": "https://vt.tiktok.com/ZS9KbaK3n/",
    "taloncamp_sg": "https://vt.tiktok.com/ZS9bmgMM2/",
    "sarun_kritaterakul": "https://vt.tiktok.com/ZS9aBHdoY/",
    "nattienote": "https://vt.tiktok.com/ZS9vSfoWE/"
}

# KOLs ที่ยังไม่โพสต์ — ลบชื่อออกเมื่อโพสต์แล้ว
NOT_POSTED_KOLS = set([])

KOL_STATUS = {
    "markc.boardgame": "Posted",
    "minkmories": "Posted",
    "dairyparty": "Posted",
    "narongrit11414": "Posted",
    "tanawatpankaew": "Posted",
    "fford._.mini": "Posted",
    "ledswu": "Posted",
    "debuam012": "Posted",
    "saruanly": "Posted",
    "tuajeed.office": "Posted",
    "miinez_": "Posted",
    "gonsalosol": "Posted",
    "sharkwow.ch": "Posted",
    "witbenmoreallright": "Posted",
    "gampamao": "Posted",
    "tatatomang": "Posted",
    "taloncamp_sg": "Posted",
    "sarun_kritaterakul": "Posted",
    "nattienote": "Posted",
}




def preserve_actual_use(html_content):
    m = re.search(r'const\s+CAMPAIGN_ACTUAL_USE_DEFAULT\s*=\s*([\d.]+)', html_content)
    return float(m.group(1)) if m else 0


def parse_existing_kol_data(html_content):
    """Parse existing KOL_DATA stats to preserve when scrape fails."""
    existing = {}
    pattern = r"\{\s*username:\s*'([^']+)'.*?followers:\s*(\d+).*?views:\s*(\d+).*?likes:\s*(\d+).*?shares:\s*(\d+).*?comments:\s*(\d+).*?saves:\s*(\d+)"
    for m in re.finditer(pattern, html_content):
        username = m.group(1)
        existing[username] = {
            'followers': int(m.group(2)),
            'views': int(m.group(3)),
            'likes': int(m.group(4)),
            'shares': int(m.group(5)),
            'comments': int(m.group(6)),
            'saves': int(m.group(7)),
        }
    return existing


def js_escape(s):
    if s is None:
        return ''
    return str(s).replace('\\', '\\\\').replace("'", "\\'")


def build_kol_entry(username, scrape_data, link='', existing_data=None):
    meta = KOL_METADATA.get(username, {})
    sd = scrape_data.get(username, {})
    ex = (existing_data or {}).get(username, {})

    display_name = meta.get('displayName', username)
    tier = meta.get('tier', 'Unknown')
    category = meta.get('category', 'Unknown')
    gender = meta.get('gender', '-')
    followers = sd.get('followers', 0) or meta.get('followers', 0)
    budget = meta.get('budget', 0)

    if username in scrape_data:
        views = sd.get('views', 0)
        likes = sd.get('likes', 0)
        shares = sd.get('shares', 0)
        comments = sd.get('comments', 0)
        saves = sd.get('saves', 0)
    else:
        views = ex.get('views', 0)
        likes = ex.get('likes', 0)
        shares = ex.get('shares', 0)
        comments = ex.get('comments', 0)
        saves = ex.get('saves', 0)

    posted = username not in NOT_POSTED_KOLS and bool(link)
    posts = 1 if posted else 0
    kpi_views = views

    status = KOL_STATUS.get(username, 'รอส่ง')
    return (
        f"  {{ username: '{js_escape(username)}', displayName: '{js_escape(display_name)}', "
        f"tier: '{js_escape(tier)}', platform: 'TikTok', category: '{js_escape(category)}', "
        f"gender: '{js_escape(gender)}', followers: {followers}, "
        f"views: {views}, likes: {likes}, shares: {shares}, "
        f"comments: {comments}, saves: {saves}, "
        f"posts: {posts}, kpi_views: {kpi_views}, "
        f"posted: {'true' if posted else 'false'}, "
        f"link: '{js_escape(link)}', budget: {budget}, "
        f"status: '{js_escape(status)}' }}"
    )


def main():
    if len(sys.argv) < 3:
        print("Usage: python3 scripts/update_dashboard.py scrape_results.json index.html")
        sys.exit(1)

    json_file = sys.argv[1]
    html_file = sys.argv[2]

    try:
        with open(json_file, 'r') as f:
            scrape_data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        scrape_data = {}

    with open(html_file, 'r', encoding='utf-8') as f:
        html = f.read()

    actual_use = preserve_actual_use(html)
    existing_data = parse_existing_kol_data(html)

    entries = []
    for username in KOL_METADATA.keys():
        link = KOL_LINKS.get(username, '')
        entry = build_kol_entry(username, scrape_data, link, existing_data)
        entries.append(entry)

    new_kol_data = "const KOL_DATA = [\n" + ",\n".join(entries) + "\n];"

    pattern = r'const\s+KOL_DATA\s*=\s*\[[\s\S]*?\];'
    html = re.sub(pattern, new_kol_data, html, count=1)

    html = re.sub(
        r'const\s+CAMPAIGN_ACTUAL_USE_DEFAULT\s*=\s*[\d.]+',
        f'const CAMPAIGN_ACTUAL_USE_DEFAULT = {actual_use}',
        html
    )

    with open(html_file, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"Dashboard updated: {html_file}")
    print(f"KOLs updated: {len(entries)}")
    print(f"Scraped data injected: {len(scrape_data)} KOL(s)")
    print(f"Actual Use preserved: {actual_use:,.0f}")


if __name__ == '__main__':
    main()
