#!/usr/bin/env python3
"""
LOTUS Snack 2026 — Update Dashboard
Read JSON from scraper → inject into KOL_DATA in index.html
Usage: python3 scripts/update_dashboard.py scrape_results.json index.html
"""

import json
import sys
import re

# ============================================================
#  KOL METADATA — fallback data for all KOLs (generated by skill)
# ============================================================
KOL_METADATA = {
    "markc.boardgame": {
        "displayName": "markc.boardgame",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 104900,
        "budget": 12000
    },
    "minkmories": {
        "displayName": "minkmories",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 363400,
        "budget": 15000
    },
    "dairyparty": {
        "displayName": "dairyparty",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 68700,
        "budget": 10000
    },
    "narongrit11414": {
        "displayName": "narongrit",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 85700,
        "budget": 16000
    },
    "tanawatpankaew": {
        "displayName": "tanawatpankaew",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 77400,
        "budget": 5000
    },
    "fford._.mini": {
        "displayName": "fford._.mini",
        "tier": "ขาไก่",
        "category": "ขาไก่",
        "gender": "-",
        "followers": 23200,
        "budget": 7000
    },
    "ledswu": {
        "displayName": "ledswu",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 138400,
        "budget": 17000
    },
    "debuam012": {
        "displayName": "debuam012",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 20600,
        "budget": 4500
    },
    "saruanly": {
        "displayName": "saruanly",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 6639,
        "budget": 7250
    },
    "tuajeed.office": {
        "displayName": "tuajeed.office",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 27000,
        "budget": 14500
    },
    "miinez_": {
        "displayName": "miinez_",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 39100,
        "budget": 15000
    },
    "gonsalosol": {
        "displayName": "gonsalosol",
        "tier": "น่องไก่",
        "category": "น่องไก่",
        "gender": "-",
        "followers": 372900,
        "budget": 26000
    },
    "sharkwow.ch": {
        "displayName": "sharkwow.ch",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 578300,
        "budget": 40000
    },
    "witbenmoreallright": {
        "displayName": "witbenmoreallright",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 1000000,
        "budget": 35000
    },
    "gampamao": {
        "displayName": "ไอ้แก้มขี้เมา",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 182600,
        "budget": 15000
    },
    "tatatomang": {
        "displayName": "tatatomang",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 186900,
        "budget": 15000
    },
    "taloncamp_sg": {
        "displayName": "ตะลอนแคมภ์",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 257100,
        "budget": 19000
    },
    "sarun_kritaterakul": {
        "displayName": "sarun_kritaterakul",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 30600,
        "budget": 9000
    },
    "nattienote": {
        "displayName": "nattienote",
        "tier": "หนังไก่",
        "category": "หนังไก่",
        "gender": "-",
        "followers": 274900,
        "budget": 22000
    }
}

KOL_LINKS = {
    "markc.boardgame": "https://vt.tiktok.com/ZS9aPr8MX/",
    "minkmories": "https://vt.tiktok.com/ZS9bLxokr/",
    "dairyparty": "https://www.tiktok.com/@dairyparty/video/7637753510116740360",
    "narongrit11414": "https://vt.tiktok.com/ZS9EsqqWw/",
    "tanawatpankaew": "https://vt.tiktok.com/ZS9KqJggx/",
    "fford._.mini": "https://vt.tiktok.com/ZS9bMV5M5/",
    "ledswu": "https://vt.tiktok.com/ZS9G9rGKX/",
    "debuam012": "https://vt.tiktok.com/ZS9bFpyNh/",
    "saruanly": "https://vt.tiktok.com/ZS9a2kjxW/",
    "tuajeed.office": "https://vt.tiktok.com/ZSxjfekwg/",
    "miinez_": "https://vt.tiktok.com/ZS9tk5kKo/",
    "gonsalosol": "https://vt.tiktok.com/ZSx8JCwkq/",
    "sharkwow.ch": "https://vt.tiktok.com/ZS9Kq6Fbf/",
    "witbenmoreallright": "https://vt.tiktok.com/ZS9aABnfe/",
    "gampamao": "https://vt.tiktok.com/ZS9aSw6mn/",
    "tatatomang": "https://vt.tiktok.com/ZS9KbaK3n/",
    "taloncamp_sg": "https://vt.tiktok.com/ZS9bmgMM2/",
    "sarun_kritaterakul": "https://vt.tiktok.com/ZS9aBHdoY/",
    "nattienote": "https://vt.tiktok.com/ZS9vSfoWE/"
}

# KOLs ที่ยังไม่โพสต์ — ลบชื่อออกเมื่อโพสต์แล้ว
NOT_POSTED_KOLS = set([])

KOL_STATUS = {
    "markc.boardgame": "Posted",
    "minkmories": "Posted",
    "dairyparty": "Posted",
    "narongrit11414": "Posted",
    "tanawatpankaew": "Posted",
    "fford._.mini": "Posted",
    "ledswu": "Posted",
    "debuam012": "Posted",
    "saruanly": "Posted",
    "tuajeed.office": "Posted",
    "miinez_": "Posted",
    "gonsalosol": "Posted",
    "sharkwow.ch": "Posted",
    "witbenmoreallright": "Posted",
    "gampamao": "Posted",
    "tatatomang": "Posted",
    "taloncamp_sg": "Posted",
    "sarun_kritaterakul": "Posted",
    "nattienote": "Posted",
}

# ============================================================
#  PHASE 2 — KOL METADATA & LINKS
# ============================================================
PHASE2_KOL_METADATA = {
    # ขาไก่ (11 KOLs)
    "nurse.enjoyea":      {"displayName": "nurse.enjoyea",      "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 504900, "budget": 30000},
    "100lowteens":        {"displayName": "100lowteens",        "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 762500, "budget": 30000},
    "joinjoy89":          {"displayName": "joinjoy89",          "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 385900, "budget": 27000},
    "sristories.official":{"displayName": "sristories.official","tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 80800,  "budget": 22000},
    "mayme_711":          {"displayName": "mayme_711",          "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 157800, "budget": 16000},
    "tima.chan":           {"displayName": "tima.chan",          "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 638200, "budget": 36000},
    "mew_natheera":       {"displayName": "mew_natheera",       "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 1600000,"budget": 35000},
    "ningninkka":         {"displayName": "ningninkka",         "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 329500, "budget": 35000},
    "pizzaplazaa":        {"displayName": "pizzaplazaa",        "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 278200, "budget": 26000},
    "i.prim":             {"displayName": "i.prim",             "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 409300, "budget": 30000},
    "bolongkinn":         {"displayName": "bolongkinn",         "tier": "ขาไก่", "category": "ขาไก่", "gender": "-", "followers": 78700,  "budget": 20000},
    # น่องไก่ (9 KOLs)
    "haruyda":            {"displayName": "haruyda",            "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 1400000,"budget": 50000},
    "plaifahhahaha":      {"displayName": "plaifahhahaha",      "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 110000, "budget": 25000},
    "chengandrock":       {"displayName": "chengandrock",       "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 730700, "budget": 40000},
    "faymily_":           {"displayName": "faymily_",           "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 308800, "budget": 40000},
    "gindaieek":          {"displayName": "gindaieek",          "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 1000000,"budget": 55000},
    "googidd":            {"displayName": "googidd",            "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 426300, "budget": 37000},
    "pankpanq":           {"displayName": "pankpanq",           "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 3661,   "budget": 17000},
    "whatpalaa":          {"displayName": "whatpalaa",           "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 20600,  "budget": 17000},
    "sweettart.tt":       {"displayName": "sweettart.tt",       "tier": "น่องไก่", "category": "น่องไก่", "gender": "-", "followers": 412500, "budget": 35000},
    # หนังไก่ (10 KOLs)
    "mild.prapaipan":     {"displayName": "กินเข้าไป",          "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 913800, "budget": 36000},
    "11.mn.84":           {"displayName": "11.mn.84",           "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 308900, "budget": 30000},
    "palmmookangrang":    {"displayName": "palmmookangrang",    "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 352500, "budget": 33000},
    "mhingkualoak":       {"displayName": "mhingkualoak",       "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 162800, "budget": 26000},
    "thintomorrow":       {"displayName": "thintomorrow",       "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 568200, "budget": 30000},
    "farbeer69":          {"displayName": "farbeer69",          "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 213100, "budget": 26000},
    "enjoyeatingclub":    {"displayName": "enjoyeatingclub",    "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 18200,  "budget": 18000},
    "ssaintst":           {"displayName": "ssaintst",           "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 116200, "budget": 16000},
    "ninkkieee":          {"displayName": "ninkkieee",          "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 48600,  "budget": 18000},
    "stampginra":         {"displayName": "stampginrai",        "tier": "หนังไก่", "category": "หนังไก่", "gender": "-", "followers": 61000,  "budget": 18000},
}

PHASE2_KOL_LINKS = {
    # ขาไก่ (10 posted)
    "nurse.enjoyea": "https://vt.tiktok.com/ZSCXV8bxS/",
    "100lowteens": "https://vt.tiktok.com/ZSCaK4qaX/",
    "joinjoy89": "https://www.tiktok.com/@joinjoy89/video/7657534776919788807",
    "sristories.official": "https://vt.tiktok.com/ZSCmW9rtB/",
    "mayme_711": "https://vt.tiktok.com/ZSCxaqXx1/",
    "tima.chan": "https://vt.tiktok.com/ZSCuefFQf/",
    "ningninkka": "https://vt.tiktok.com/ZSCmc9UY2/",
    "pizzaplazaa": "https://vt.tiktok.com/ZSCuJN1pr/",
    "i.prim": "https://vt.tiktok.com/ZSCxGy9Ds/",
    "bolongkinn": "https://vt.tiktok.com/ZSCxNLp27/",
    # น่องไก่ (8 posted)
    "haruyda": "https://vt.tiktok.com/ZSCmK3DTB/",
    "plaifahhahaha": "https://vt.tiktok.com/ZSCuj1FVw/",
    "chengandrock": "https://vt.tiktok.com/ZSCm7cu3t/",
    "gindaieek": "https://vt.tiktok.com/ZSCuMCC3W/",
    "googidd": "https://vt.tiktok.com/ZSCmsHPmh/",
    "pankpanq": "https://vt.tiktok.com/ZSCXsVaYU/",
    "whatpalaa": "https://vt.tiktok.com/ZSC9NddGN/",
    "sweettart.tt": "https://vt.tiktok.com/ZSCxj7s87/",
    # หนังไก่ (5 posted)
    "11.mn.84": "https://vt.tiktok.com/ZSCvyMdnU/",
    "palmmookangrang": "https://vt.tiktok.com/ZSCuDkWrY/",
    "enjoyeatingclub": "https://vt.tiktok.com/ZSCujUmoF/",
    "ssaintst": "https://vt.tiktok.com/ZSCmwDGth/",
    "stampginra": "https://vt.tiktok.com/ZSCQT9qpH/",
    "mew_natheera": "https://vt.tiktok.com/ZSCweqNpu/",
    "faymily_": "https://vt.tiktok.com/ZSXkSk17q/",
    "mild.prapaipan": "https://vt.tiktok.com/ZSCKKRbyt/",
    "mhingkualoak": "https://vt.tiktok.com/ZSXe3jTp8/",
    "thintomorrow": "https://vt.tiktok.com/ZSXDt25E6/",
    "farbeer69": "https://vt.tiktok.com/ZSXxqjvra/",
    "ninkkieee": "https://vt.tiktok.com/ZSCoSeMU8/",
}

# 7 KOLs ที่ยังไม่โพสต์ Phase 2
PHASE2_NOT_POSTED_KOLS = set()

PHASE2_KOL_STATUS = {k: "โพสต์แล้ว" for k in PHASE2_KOL_LINKS}
PHASE2_KOL_STATUS.update({k: "รอโพสต์" for k in PHASE2_NOT_POSTED_KOLS})




def preserve_actual_use(html_content):
    m = re.search(r'const\s+CAMPAIGN_ACTUAL_USE_DEFAULT\s*=\s*([\d.]+)', html_content)
    return float(m.group(1)) if m else 0


def parse_existing_kol_data(html_content):
    """Parse existing KOL_DATA stats to preserve when scrape fails."""
    existing = {}
    pattern = r"\{\s*username:\s*'([^']+)'.*?followers:\s*(\d+).*?views:\s*(\d+).*?likes:\s*(\d+).*?shares:\s*(\d+).*?comments:\s*(\d+).*?saves:\s*(\d+)"
    for m in re.finditer(pattern, html_content):
        username = m.group(1)
        existing[username] = {
            'followers': int(m.group(2)),
            'views': int(m.group(3)),
            'likes': int(m.group(4)),
            'shares': int(m.group(5)),
            'comments': int(m.group(6)),
            'saves': int(m.group(7)),
        }
    return existing


def js_escape(s):
    if s is None:
        return ''
    return str(s).replace('\\', '\\\\').replace("'", "\\'")


def build_kol_entry(username, scrape_data, link='', existing_data=None,
                    metadata_dict=None, not_posted_set=None, status_dict=None):
    """Build a single KOL JS object string. Works for both Phase 1 and Phase 2."""
    if metadata_dict is None:
        metadata_dict = KOL_METADATA
    if not_posted_set is None:
        not_posted_set = NOT_POSTED_KOLS
    if status_dict is None:
        status_dict = KOL_STATUS

    meta = metadata_dict.get(username, {})
    sd = scrape_data.get(username, {})
    ex = (existing_data or {}).get(username, {})

    display_name = meta.get('displayName', username)
    tier = meta.get('tier', 'Unknown')
    category = meta.get('category', 'Unknown')
    gender = meta.get('gender', '-')
    followers = sd.get('followers', 0) or meta.get('followers', 0)
    budget = meta.get('budget', 0)

    if username in scrape_data:
        views = sd.get('views', 0)
        likes = sd.get('likes', 0)
        shares = sd.get('shares', 0)
        comments = sd.get('comments', 0)
        saves = sd.get('saves', 0)
    else:
        views = ex.get('views', 0)
        likes = ex.get('likes', 0)
        shares = ex.get('shares', 0)
        comments = ex.get('comments', 0)
        saves = ex.get('saves', 0)

    posted = username not in not_posted_set and bool(link)
    posts = 1 if posted else 0
    kpi_views = views

    status = status_dict.get(username, 'รอส่ง')
    return (
        f"  {{ username: '{js_escape(username)}', displayName: '{js_escape(display_name)}', "
        f"tier: '{js_escape(tier)}', platform: 'TikTok', category: '{js_escape(category)}', "
        f"gender: '{js_escape(gender)}', followers: {followers}, "
        f"views: {views}, likes: {likes}, shares: {shares}, "
        f"comments: {comments}, saves: {saves}, "
        f"posts: {posts}, kpi_views: {kpi_views}, "
        f"posted: {'true' if posted else 'false'}, "
        f"link: '{js_escape(link)}', budget: {budget}, "
        f"status: '{js_escape(status)}' }}"
    )


def parse_existing_phase2_data(html_content):
    """Parse existing PHASE2_KOL_DATA stats to preserve when scrape fails."""
    existing = {}
    # Find the PHASE2_KOL_DATA block
    m = re.search(r'const\s+PHASE2_KOL_DATA\s*=\s*\[([\s\S]*?)\];', html_content)
    if not m:
        return existing
    block = m.group(1)
    pattern = r"\{\s*username:\s*'([^']+)'.*?followers:\s*(\d+).*?views:\s*(\d+).*?likes:\s*(\d+).*?shares:\s*(\d+).*?comments:\s*(\d+).*?saves:\s*(\d+)"
    for match in re.finditer(pattern, block):
        username = match.group(1)
        existing[username] = {
            'followers': int(match.group(2)),
            'views': int(match.group(3)),
            'likes': int(match.group(4)),
            'shares': int(match.group(5)),
            'comments': int(match.group(6)),
            'saves': int(match.group(7)),
        }
    return existing


def main():
    if len(sys.argv) < 3:
        print("Usage: python3 scripts/update_dashboard.py scrape_results.json index.html")
        sys.exit(1)

    json_file = sys.argv[1]
    html_file = sys.argv[2]

    # Load Phase 1 scrape data
    try:
        with open(json_file, 'r') as f:
            scrape_data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        scrape_data = {}

    # Load Phase 2 scrape data
    p2_json = json_file.replace('.json', '_p2.json')
    try:
        with open(p2_json, 'r') as f:
            p2_scrape_data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        p2_scrape_data = {}

    with open(html_file, 'r', encoding='utf-8') as f:
        html = f.read()

    actual_use = preserve_actual_use(html)

    # ── Phase 1 ──
    existing_data = parse_existing_kol_data(html)
    entries = []
    for username in KOL_METADATA.keys():
        link = KOL_LINKS.get(username, '')
        entry = build_kol_entry(username, scrape_data, link, existing_data)
        entries.append(entry)

    new_kol_data = "const PHASE1_KOL_DATA = [\n" + ",\n".join(entries) + "\n];"
    pattern = r'const\s+PHASE1_KOL_DATA\s*=\s*\[[\s\S]*?\];'
    html = re.sub(pattern, new_kol_data, html, count=1)

    # ── Phase 2 ──
    p2_existing = parse_existing_phase2_data(html)
    # Group by category for comments
    categories = {'ขาไก่': [], 'น่องไก่': [], 'หนังไก่': []}
    for username in PHASE2_KOL_METADATA.keys():
        cat = PHASE2_KOL_METADATA[username].get('category', '')
        if cat in categories:
            categories[cat].append(username)

    # Build Phase 2 output with category comments (no comma after comments)
    p2_output_lines = []
    all_entries_flat = []
    for cat_name, cat_users in categories.items():
        p2_output_lines.append(f"  // {cat_name} ({len(cat_users)} KOLs)")
        for username in cat_users:
            link = PHASE2_KOL_LINKS.get(username, '')
            entry = build_kol_entry(
                username, p2_scrape_data, link, p2_existing,
                metadata_dict=PHASE2_KOL_METADATA,
                not_posted_set=PHASE2_NOT_POSTED_KOLS,
                status_dict=PHASE2_KOL_STATUS
            )
            p2_output_lines.append(entry)
            all_entries_flat.append(username)

    # Join lines: commas only between object entries, not after comments
    p2_body = ""
    for i, line in enumerate(p2_output_lines):
        p2_body += line
        # Add comma after entry lines if there's another entry coming
        if line.strip().startswith('{'):
            # Check if there's another entry after this (skip comments)
            has_more_entries = False
            for j in range(i + 1, len(p2_output_lines)):
                if p2_output_lines[j].strip().startswith('{'):
                    has_more_entries = True
                    break
            if has_more_entries:
                p2_body += ","
        p2_body += "\n"

    new_p2_data = "const PHASE2_KOL_DATA = [\n" + p2_body + "];"
    p2_pattern = r'const\s+PHASE2_KOL_DATA\s*=\s*\[[\s\S]*?\];'
    html = re.sub(p2_pattern, new_p2_data, html, count=1)

    # Preserve actual use
    html = re.sub(
        r'const\s+CAMPAIGN_ACTUAL_USE_DEFAULT\s*=\s*[\d.]+',
        f'const CAMPAIGN_ACTUAL_USE_DEFAULT = {actual_use}',
        html
    )

    with open(html_file, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"Dashboard updated: {html_file}")
    print(f"Phase 1 KOLs updated: {len(entries)}")
    print(f"Phase 1 scraped: {len(scrape_data)} KOL(s)")
    print(f"Phase 2 KOLs updated: {len(PHASE2_KOL_METADATA)}")
    print(f"Phase 2 scraped: {len(p2_scrape_data)} KOL(s)")
    print(f"Actual Use preserved: {actual_use:,.0f}")


if __name__ == '__main__':
    main()
